basePath: /
definitions:
  handlers.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.PaginatedBooksResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Book'
        type: array
      metadata:
        additionalProperties: true
        type: object
    type: object
  models.Author:
    properties:
      bio:
        type: string
      id:
        type: integer
      name:
        maxLength: 100
        minLength: 2
        type: string
    required:
    - name
    type: object
  models.Book:
    properties:
      author:
        allOf:
        - $ref: '#/definitions/models.Author'
        description: |-
          Author is a pointer to the Author model for nesting author information in responses.
          The `omitempty` tag prevents it from being included in the JSON if it's nil.
      author_id:
        description: |-
          AuthorID is used for data input when creating/updating a book.
          It links the book to an author in the authors table.
        type: integer
      id:
        description: ID is the unique identifier for the book.
        type: integer
      isbn:
        description: ISBN is the International Standard Book Number.
        type: string
      published_date:
        description: PublishedDate is the date the book was published, in YYYY-MM-DD
          format.
        type: string
      stock:
        description: Stock is the number of available copies of the book.
        minimum: 0
        type: integer
      title:
        description: Title is the title of the book.
        maxLength: 100
        minLength: 2
        type: string
    required:
    - author_id
    - isbn
    - published_date
    - title
    type: object
  models.Loan:
    properties:
      book:
        $ref: '#/definitions/models.Book'
      book_id:
        type: integer
      id:
        type: integer
      loan_date:
        type: string
      return_date:
        description: |-
          ReturnDate is a pointer to time.Time to allow for null values from the database.
          The omitempty tag ensures it's not included in the JSON response if it's null.
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      id:
        description: ID is the unique identifier for the user.
        type: integer
      role:
        type: string
      username:
        description: Username is the unique name for the user account.
        maxLength: 50
        minLength: 3
        type: string
    required:
    - username
    type: object
info:
  contact: {}
  description: This is the API for the Librarium application.
  title: Librarium API
  version: "1.0"
paths:
  /authors:
    get:
      consumes:
      - application/json
      description: Get a list of all authors.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Author'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List authors
      tags:
      - Authors
    post:
      consumes:
      - application/json
      description: Adds a new author to the collection. Requires librarian role.
      parameters:
      - description: Author object to be created
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/models.Author'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Author'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new author
      tags:
      - Authors
  /authors/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a single author by their unique ID.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Author'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get an author by ID
      tags:
      - Authors
  /books:
    get:
      consumes:
      - application/json
      description: Get a paginated, filtered, and sorted list of books.
      parameters:
      - description: Filter by book title (case-insensitive, partial match)
        in: query
        name: title
        type: string
      - description: Filter by author name (case-insensitive, partial match)
        in: query
        name: author
        type: string
      - description: 'Field to sort by. Allowed values: title, author, published_date,
          stock'
        in: query
        name: sort
        type: string
      - description: 'Sort order. Allowed values: asc, desc'
        in: query
        name: order
        type: string
      - description: Page number for pagination
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PaginatedBooksResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List books
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Adds a new book to the collection. Requires librarian role.
      parameters:
      - description: 'Book object to be created. Note: ''id'' and ''author'' fields
          are ignored.'
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Book'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new book
      tags:
      - Books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a book from the collection. Requires librarian role.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a book
      tags:
      - Books
    get:
      consumes:
      - application/json
      description: Retrieves the details of a single book by its unique ID.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a book by ID
      tags:
      - Books
    put:
      consumes:
      - application/json
      description: Updates the details of an existing book. Requires librarian role.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Book object with updated details
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a book
      tags:
      - Books
  /loans:
    get:
      consumes:
      - application/json
      description: Get a list of all loans in the system. Can be filtered by status.
      parameters:
      - description: 'Filter by loan status. Allowed values: active, returned'
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Loan'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List all loans (Admin)
      tags:
      - Loans
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token.
      parameters:
      - description: User Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - Authentication
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user account with the 'member' role.
      parameters:
      - description: User Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.Credentials'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Authentication
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
